services:
  jobbix:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - shared-network

networks:
  shared-network:
    external: true
