version: "3.8"

services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    restart: always
    # privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    # network_mode: bridge
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
    # Doc https://github.com/qdm12/gluetun
    env_file: env_vars/.env-proxy
    expose:
      - 2090
      - 5566
      - 8888 #HTTP proxy port
      - 9050 #Tor socks port
      - 9051 #Tor control port
    ports:
      - "2090:2090"
      - "5566:5566"
      - "8888:8888" #HTTP proxy port
      - "9051:9051"
    networks:
      - shared-network

  # Doc: https://github.com/zet4/alpine-tor
  # Uses gluetun VPN network, which will only be online when VPN connects.
  # To check status, run docker-compose -> http://localhost:2090/ for HAProxy stats
  tor-proxy:
    container_name: tor-proxy
    build:
      context: ./alpine-tor
      dockerfile: Dockerfile
    stop_grace_period: 1s
    env_file: env_vars/.env-proxy
    volumes:
      - ./torrc:/etc/tor/torrc
    network_mode: service:gluetun
    depends_on:
      - gluetun

networks:
  shared-network:
    external: true
